type_counts = df["type"].value_counts()
plt.figure(figsize=(6,4))
plt.bar(type_counts.index , type_counts.values , color = ["skyblue" , "orange"])
plt.title("Number of movies vs tv shows on netflix")
plt.xlabel("Type")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("Movies_vs_Tvshows.png")
plt.show() 


rating_counts = df["rating"].value_counts()
plt.figure(figsize=(8,6))
plt.pie(rating_counts , labels  = rating_counts.index , autopct="%1.1f%%",startangle=90 )
plt.title("Percentage of content rating")
plt.tight_layout()
plt.savefig("Content_rating.png")
plt.show()


movie_df = df[df["type"] == "Movie"].copy()
movie_df["duration_int"] = movie_df["duration"].str.replace(" min","").astype(int)
plt.figure(figsize=(8,6))
plt.hist(movie_df["duration_int"] , bins=30 , color = "purple" , edgecolor = "black")
plt.title("Distrubition of movies duration")
plt.xlabel("Duration (in minutes)")
plt.ylabel("Number of movies")
plt.tight_layout()
plt.savefig("Movies_duration_histogram.png")
plt.show() 
